MovieCommentateApp/Models/Movie.cs
namespace MovieReviewApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; } = string.Empty;
        public int Year { get; set; } 
        public string? PosterImage { get; set; } = string.Empty;
        public int GenreId { get; set; }
        public Genre Genre { get; set; }
        public List<Comment> Comments { get; set; }= new List<Comment>();
        public List<ActorMovie> Actors { get; set; } = new List<ActorMovie>();
    }
}

MovieCommentateApp/Areas/Admin/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MovieReviewApp.Areas.Admin.Dtos.Movie;
using MovieReviewApp.Areas.Admin.Interfaces;
using MovieReviewApp.Areas.Admin.Mappers;
using MovieReviewApp.Interfaces;
using MovieReviewApp.Models;
using NuGet.Versioning;

namespace MovieReviewApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MovieController : Controller
    {
        private readonly MovieReviewApp.Areas.Admin.Interfaces.IMovieRepository _movieRepository;
        private readonly MovieReviewApp.Interfaces.IGenreRepository _genreRepository;

        public MovieController(Interfaces.IMovieRepository movieRepository, MovieReviewApp.Interfaces.IGenreRepository genreRepository)
        {
            _movieRepository = movieRepository;
            _genreRepository = genreRepository;
        }

        public async Task<IActionResult> Movies()
        {
            var list = await _movieRepository.GetAllAsync();
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ViewBag.Genres = await _genreRepository.GetAllAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CreateMovieDto createMovieDto, IFormFile? formFile)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genres = await _genreRepository.GetAllAsync();
                return View();
            }

            string newMovieFile = _movieRepository.ImageAdd(formFile);
            createMovieDto.PosterImage = newMovieFile;
            await _movieRepository.CreateAsync(createMovieDto);
            return RedirectToAction("Movies", "Movie", new { area = "Admin" });

        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _movieRepository.GetByIdAsync(id);
            ViewBag.Genres = await _genreRepository.GetAllAsync();
            if (model==null)
                return RedirectToAction("Error", "Error", new { area = "" });
            return View(model.MovieToUpdateDto());
        }
        [HttpPost]
        public async Task<IActionResult> Update(UpdateMovieDto updateMovieDto,IFormFile? formFile)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genres = await _genreRepository.GetAllAsync();
                return View(updateMovieDto);
            }

            var oldmodel = await _movieRepository.GetByIdAsync(updateMovieDto.Id);

            if (oldmodel == null)
                return RedirectToAction("Error", "Error", new { area = "" });

            string newMovieFile="";
            if (formFile != null && oldmodel.PosterImage!=null)
            {
                newMovieFile = _movieRepository.ImageUpdate(formFile, oldmodel.PosterImage);
            }
            else if (formFile != null)
            {
                newMovieFile = _movieRepository.ImageAdd(formFile);
            }
            else if (oldmodel.PosterImage!=null)
            {
                newMovieFile=oldmodel.PosterImage;
            }

            updateMovieDto.PosterImage= newMovieFile;
            await _movieRepository.UpdateAsync(updateMovieDto);

            return RedirectToAction("Movies", "Movie", new { area = "Admin" });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _movieRepository.DeleteAsync(id);
            if (model == null)
                return RedirectToAction("Error", "Error", new { area = "" });

            return RedirectToAction("Movies", "Movie", new { area = "Admin" });
        }
    }
}

MovieCommentateApp/Controllers/ActorController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieReviewApp.Interfaces;
using MovieReviewApp.Models;

namespace MovieReviewApp.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorRepository _actorRepository;
        private readonly UserManager<AppUser> _userManager;

        public ActorController(IActorRepository actorRepository, UserManager<AppUser> userManager)
        {
            _actorRepository = actorRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            var actor=await _actorRepository.GetByIdAsync(id);
            if (actor==null)
            {
                return RedirectToAction("Error", "Error");
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Error", "Error");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];
            return View(actor);
        }
    }
}

MovieCommentateApp/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieReviewApp.Dtos.Comment;
using MovieReviewApp.Interfaces;

namespace MovieReviewApp.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly ICommentRepository _commentRepository;

        public CommentController(ICommentRepository commentRepository)
        {
            _commentRepository = commentRepository;
        }

        [HttpPost]
        public async Task<IActionResult> CommentAdd(CommentDto commentDto)
        {
            if (!ModelState.IsValid)
            {
                TempData["ModelStateErrors"] = ModelState.Values
            .SelectMany(v => v.Errors)
            .Select(e => e.ErrorMessage)
            .ToList();
            }
            else
            {
                await _commentRepository.CreateAsync(commentDto);
            }
            return RedirectToAction("MovieDetails", "Movie", new { id = commentDto.MovieId });
        }
    }
}

MovieCommentateApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieReviewApp.Dtos.Comment;
using MovieReviewApp.Dtos.Movie;
using MovieReviewApp.Interfaces;
using MovieReviewApp.Models;
using System.Security.Claims;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace MovieReviewApp.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;
        private readonly IGenreRepository _genreRepo;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public MovieController(IMovieRepository movieRepo, IGenreRepository genreRepo, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _movieRepo = movieRepo;
            _genreRepo = genreRepo;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> Movies()
        {
            ViewBag.Genres = await _genreRepo.GetAllAsync();
            var list=await _movieRepo.GetAllAsync();

            var query = new QueryMovieDto();
            ViewBag.LastQuery = query;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Login","Account");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];
            return View(list);
        }
        [HttpPost]
        public async Task<IActionResult> Movies(QueryMovieDto query)
        {
            ViewBag.Genres = await _genreRepo.GetAllAsync();
            //for save last query
            ViewBag.LastQuery = query;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];

            List<Movie> list;
            if (!ModelState.IsValid)
            {
                list = new List<Movie>();
                return View(list);
            }

            list = await _movieRepo.GetAllAsync(query);
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> MovieDetails(int id)
        {
            var movie = await _movieRepo.GetByIdWithAllAsync(id);
            if (movie==null)
            {
                return RedirectToAction("Error", "Error");
            }
            ViewData["userId"] = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Error", "Error");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];
            return View(movie);
        }
    }
}

MovieCommentateApp/Views/Movie/MovieDetails.cshtml
@using MovieReviewApp.Models
@model Movie
@{
    ViewData["Title"] = "MovieDetails";
    if (ViewBag.userRole == "User")
    {
        Layout = "~/Views/Shared/UserLayout.cshtml";
    }
    else if (ViewBag.userRole == "Admin")
    {
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }
}

<div class="row">
    <div class="movie-details col-md-4">
        <div class="w-100">
            @if (Model.PosterImage == string.Empty)
            {
                <img style="width:100%" src="~/img/nophoto.png" />
            }
            else
            {
                <img style="width:100%" src="~/img/Movie/@Model.PosterImage" />
            }
        </div>
        <div>
            <h5>@Model.Name</h5>
            <table class="table table-bordered">
                <tr>
                    <th>Genre</th>
                    <td>@Model.Genre.Name</td>
                </tr>
                <tr>
                    <th>Year</th>
                    <td>@Model.Year</td>
                </tr>
                <tr>
                    <th>Actors</th>
                    <td>
                        <ul>
                            @foreach (var actor in Model.Actors)
                            {
                                <li><a asp-controller="Actor" asp-action="Index" asp-route-id="@actor.Actor.Id">@actor.Actor.FullName</a></li>
                            }
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>@Model.Description</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="comment-list col-md-8">
        <div class="row d-flex justify-content-center">
            <div class="col-md-11 col-lg-10">
                <div class="card shadow-0 border" style="background-color: #f0f2f5;">
                    <div class="card-body p-4">
                        @if (ViewData["userId"] != null)
                        {
                            <form method="post" class="form-outline mb-4" asp-action="CommentAdd" asp-controller="Comment">
                                <input type="text" class="form-control" placeholder="Type comment..." name="Text" />
                                <select class="form-control my-4" name="Rating" required>
                                    <option value="" selected disabled>Rating</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                                <input type="hidden" name="UserId" value="@ViewData["userId"]" />
                                <input type="hidden" name="MovieId" value="@Model.Id"/>
                                <input type="submit" value="Send" class="btn btn-success" />
                                @if (TempData["ModelStateErrors"] != null)
                                {
                                    var errors = (string[])TempData["ModelStateErrors"];
                                    <div class="alert alert-danger">
                                        @for (int i = 0; i < errors.Length; i++)
                                        {
                                            <div>@errors[i]</div>
                                        }
                                    </div>
                                }
                            </form>
                        }
                        @foreach (var comment in Model.Comments)
                        {
                            <div class="card mb-4">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <p class="col-md-8">@comment.Text</p>
                                        <p class="small mb-0 ms-2 col-md-3">@comment.Date</p>
                                    </div>
                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex flex-row align-items-center">
                                            <b class="small mb-0 ms-2">@comment.User.UserName</b>
                                        </div>
                                        <div class="d-flex flex-row align-items-center">
                                            <i class="fa-solid fa-star" style="margin-top: -0.16rem;color: #FFD43B;"></i>
                                            <p class="small text-muted mb-0">@comment.Rating</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MovieCommentateApp/Views/Movie/Movies.cshtml
@using MovieReviewApp.Models
@model List<Movie>
@{
    Layout = "~/Views/Shared/UserLayout.cshtml";
    if (ViewBag.userRole == "User")
    {
        Layout = "~/Views/Shared/UserLayout.cshtml";
    }
    else if (ViewBag.userRole == "Admin")
    {
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }
}
<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Movie List Filter</h5>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="Movie" asp-action="Movies">
                    <div class="row mb-3">
                        <div class="form-group col-md-4">
                            <label for="genreId">Genre</label>
                            <select class="form-control" name="GenreId">
                                <option value="0">All Genres</option>
                                @foreach (Genre genre in ViewBag.Genres)
                                {
                                    if (ViewBag.LastQuery.GenreId==genre.Id)
                                    {
                                        <option value="@genre.Id" selected>@genre.Name</option>
                                    }
                                    else
                                    {
                                        <option value="@genre.Id">@genre.Name</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="year">Year</label>
                            <input type="number" class="form-control" name="Year" value="@ViewBag.LastQuery.Year">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="name">Movie Name</label>
                            <input type="text" class="form-control" name="Name" value="@ViewBag.LastQuery.Name">
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-center">
                        <div class="form-group col-md-4">
                            <label for="year">Page Number</label>
                            <input type="number" class="form-control" name="PageNumber" value="@ViewBag.LastQuery.PageNumber">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="name">Page Size</label>
                            <input type="number" class="form-control" name="PageSize" value="@ViewBag.LastQuery.PageSize">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Apply Filter</button>
                    @if (ViewData.ModelState.ErrorCount > 0)
                    {
                        <div class="alert alert-danger mt-3" role="alert">
                            @foreach (var modelState in ViewData.ModelState.Values)
                            {
                                foreach (var error in modelState.Errors)
                                {
                                    <div>@error.ErrorMessage</div>
                                }
                            }
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>
@if (Model.Count == 0)
{
    <h5 class="text-center">There is no movie by these filters</h5>
}
else
{
    <div class="row card-container">
        @foreach (var movie in Model)
        {
            <div class="col-md-4 mb-4 movie-card">
                <div class="card">
                    @if (movie.PosterImage == string.Empty)
                    {
                        <img src="~/img/nophoto.png" class="card-img-top">
                    }
                    else
                    {
                        <img src="~/img/Movie/@movie.PosterImage" class="card-img-top">
                    }
                    <div class="card-body">
                        <a asp-controller="Movie" asp-action="MovieDetails" asp-route-id="@movie.Id">
                            <h5 class="card-title">@movie.Name</h5>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
}