MovieCommentateApp/Controllers/ActorController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieReviewApp.Interfaces;
using MovieReviewApp.Models;

namespace MovieReviewApp.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorRepository _actorRepository;
        private readonly UserManager<AppUser> _userManager;

        public ActorController(IActorRepository actorRepository, UserManager<AppUser> userManager)
        {
            _actorRepository = actorRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            var actor=await _actorRepository.GetByIdAsync(id);
            if (actor==null)
            {
                return RedirectToAction("Error", "Error");
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Error", "Error");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];
            return View(actor);
        }
    }
}

MovieCommentateApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieReviewApp.Dtos.Comment;
using MovieReviewApp.Dtos.Movie;
using MovieReviewApp.Interfaces;
using MovieReviewApp.Models;
using System.Security.Claims;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace MovieReviewApp.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;
        private readonly IGenreRepository _genreRepo;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public MovieController(IMovieRepository movieRepo, IGenreRepository genreRepo, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _movieRepo = movieRepo;
            _genreRepo = genreRepo;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> Movies()
        {
            ViewBag.Genres = await _genreRepo.GetAllAsync();
            var list=await _movieRepo.GetAllAsync();

            var query = new QueryMovieDto();
            ViewBag.LastQuery = query;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Login","Account");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];
            return View(list);
        }
        [HttpPost]
        public async Task<IActionResult> Movies(QueryMovieDto query)
        {
            ViewBag.Genres = await _genreRepo.GetAllAsync();
            //for save last query
            ViewBag.LastQuery = query;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];

            List<Movie> list;
            if (!ModelState.IsValid)
            {
                list = new List<Movie>();
                return View(list);
            }

            list = await _movieRepo.GetAllAsync(query);
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> MovieDetails(int id)
        {
            var movie = await _movieRepo.GetByIdWithAllAsync(id);
            if (movie==null)
            {
                return RedirectToAction("Error", "Error");
            }
            ViewData["userId"] = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Error", "Error");
            }
            var roles = await _userManager.GetRolesAsync(user);
            ViewBag.userRole = roles[0];
            return View(movie);
        }
    }
}

MovieCommentateApp/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="https://kit.fontawesome.com/92a3885c97.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</head>
<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a asp-area="" asp-action="Movies" asp-controller="Movie" class="navbar-brand">Home</a>
            <a asp-area="Admin" asp-action="Users" asp-controller="User" class="navbar-brand">Users</a>
            <a asp-area="Admin" asp-action="Movies" asp-controller="Movie" class="navbar-brand">Movies</a>
            <a asp-area="Admin" asp-action="Actors" asp-controller="Actor" class="navbar-brand">Actors</a>
            <a asp-area="Admin" asp-action="Genres" asp-controller="Genre" class="navbar-brand">Genres</a>
            <div>
                <form asp-area="" asp-action="Logout" asp-controller="Account">
                    <input type="submit" class="btn btn-danger mx-3" value="Logout">
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="https://kit.fontawesome.com/92a3885c97.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</body>
</html>

MovieCommentateApp/Views/Shared/EntryLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Form</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <!-- Include Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

MovieCommentateApp/Views/Shared/UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="https://kit.fontawesome.com/92a3885c97.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</head>
<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand">Movies</a>
            <div>
                <form>
                    <input type="submit" class="btn btn-danger mx-3" value="Logout">
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="https://kit.fontawesome.com/92a3885c97.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</body>
</html>